[package]
name = "monty"
version = "1.0.0"
edition = "2021"
authors = ["Jamie Whiting"]

[profile.release]
panic = 'abort'
strip = true
lto = true
codegen-units = 1

[features]
embed = []
datagen = []
uci-minimal = []
tunable = []

[workspace]
members = ["datagen", "train/policy", "train/value"]
resolver = "2"

[build-dependencies]
sha2 = "0.10.8"
[dependencies]
rand = "0.9.0-alpha.2"